# Generated by Django 2.1.7 on 2019-03-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190225_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='animals/default.jpg', max_length=500, upload_to='animals'),
        ),
    ]
